version: "3"

services:
  vv:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/nhs-virtual-visit-dev
      - TEST_DATABASE_URL=postgresql://postgres:postgres@postgres/nhs-virtual-visit-test
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/db
      - ./db/docker-data:/var/lib/postgresql/data
